import '../styles/scss/customBootstrap.scss';
import '../styles/scss/index.scss';
import type { AppProps } from 'next/app';
import Head from 'next/head';


export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Sien</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ISO_512px.png" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
